import React from 'react';
import Navbar from '../components/Navbar';
import './Legal.css';

const Terms = () => {
  return (
    <div className="legal-page">
      <Navbar />
      <div className="legal-container fade-in">
        <div className="legal-header">
          <h1>Terms & Conditions</h1>
          <p>Last Updated: May 18, 2026</p>
        </div>
        <div className="legal-content">
          <p>Welcome to Momentix. By accessing or using our website and services (collectively, the "Service"), you agree to be bound by these Terms & Conditions ("Terms"). If you do not agree to these Terms, please do not use the Service.</p>

          <h2>1. Account Eligibility and Security</h2>
          <p><strong>Age Requirement:</strong> You must be at least 13 years old (or the minimum age of digital consent in your country) to use this Service.</p>
          <p><strong>Account Responsibility:</strong> When you create an account via email or Google OAuth, you are responsible for maintaining the confidentiality of your credentials. You agree to accept responsibility for all activities that occur under your account.</p>

          <h2>2. User-Generated Content & AI Processing</h2>
          <p><strong>Your Content:</strong> You retain full ownership of all text, data, memories, and photos you upload to Momentix ("User Content").</p>
          <p><strong>AI Narrative Generation:</strong> Momentix uses third-party AI services (including the Google Gemini API) to transform your memories and photos into narrative stories. By uploading User Content, you grant Momentix a worldwide, non-exclusive, royalty-free license to process, format, and transmit your data to our AI sub-processors solely for the purpose of generating your stories.</p>
          <p><strong>Ownership of Generated Stories:</strong> You own the final narrative text generated by the Service. However, due to the nature of machine learning, you acknowledge that AI-generated text may not be unique, and the Service may generate similar content for other users based on different inputs.</p>

          <h2>3. Prohibited Conduct</h2>
          <p>You agree not to upload, post, or share any User Content that:</p>
          <ul>
            <li>Infringes on any third party's intellectual property, privacy, or publicity rights.</li>
            <li>Contains sexually explicit content, extreme violence, or depicts exploitation or abuse.</li>
            <li>Is defamatory, hateful, discriminatory, or promotes illegal acts.</li>
            <li>Attempts to reverse-engineer, disrupt, or bypass the security or rate-limiting thresholds of the Momentix platform.</li>
          </ul>

          <h2>4. Storage and Sharing</h2>
          <p><strong>Public Sharing:</strong> Momentix allows you to generate public share links for your stories. Once a link is generated, anyone with access to that link can view the photos and narrative associated with that story. You are solely responsible for the links you choose to share.</p>
          <p><strong>Data Availability:</strong> While we utilize secure cloud storage (Supabase), Momentix is an MVP platform and is not intended as a permanent data backup service. We reserve the right to establish storage limits or remove inactive accounts after reasonable notice.</p>

          <h2>5. Limitation of Liability</h2>
          <p>The Service and AI-generated narratives are provided on an "AS IS" and "AS AVAILABLE" basis. Momentix makes no guarantees regarding the historical accuracy, emotional suitability, or continuous availability of the AI-generated content. To the maximum extent permitted by law, Momentix shall not be liable for any indirect, incidental, or consequential damages resulting from your use of the Service.</p>

          <h2>6. Changes to Terms</h2>
          <p>We reserve the right to modify these Terms at any time. We will notify you of any major updates by updating the "Last Updated" date at the top of this page or via in-app notification.</p>
        </div>
      </div>
    </div>
  );
};

export default Terms;
